ARG CONTAINER_REGISTRY=quay.io
FROM $CONTAINER_REGISTRY/centos/centos:stream9

# NOTE: CentOS Stream 9 is still under heavy development
# hadolint ignore=DL3041
RUN <<EOF
  dnf --allowerasing  -y install \
	binutils \
	ca-certificates \
	cronie \
	curl \
	dmidecode \
	e2fsprogs \
	ethtool \
	file \
	glibc-langpack-en \
	gnupg2 \
	hostname \
	initscripts \
	iproute \
	iptables \
	iputils \
	lsof \
	nc \
	net-tools \
	nmap \
	openssl \
	passwd \
	procps \
	strace \
	sudo \
	systemd-sysv \
	systemd-udev \
	tcpdump \
	telnet \
	util-linux \
	vim-minimal \
	wget \
	libxcrypt-compat \
	which
  dnf upgrade -y
  dnf clean all
  rm -rf /var/log/*
  find /etc/systemd/system \
	/lib/systemd/system \
	-path '*.wants/*' \
	\( -name '*getty*' \
	-or -name '*dnf-makecache*' \
	-or -name '*kdump*' \
	-or -name '*systemd-logind*' \
	-or -name '*systemd-vconsole-setup*' \
	-or -name '*systemd-readahead*' \
	-or -name '*udev*' \) \
	-exec rm -v {} \;
  systemctl set-default multi-user.target
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service systemd-journal-flush.service	
EOF

CMD [ "/usr/lib/systemd/systemd" ]
