# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io/boxcutter
FROM $CONTAINER_REGISTRY/buildpack-deps:noble-curl

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		mercurial \
		openssh-client \
		subversion \
		\
# procps is very common in build systems, and is a reasonably small package
		procps \
	; \
	rm -rf /var/lib/apt/lists/*
