# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/busybox:1.36.0

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Cinc Client is an automation platform built from Chef Infra"

ARG VERSION=16.7.61
ARG SHA256_AMD64=4214edc9adf069aeae843dff192358b79cdc18f99a8baa62eec4aeb856b644af
ARG SHA256_AARCH64=81bd5dcc746d1c8693d43a6d6bd54e6278c88407e563d713ec6da09638ffff93
# This argument is automatically populated by BuildKit
ARG TARGETARCH

# We're using busybox with /bin/sh so DL4006 does not apply
# hadolint ignore=DL4006
RUN <<EOF
  case "$TARGETARCH" in \
    amd64) \
      CINC_URL=http://ftp-osl.osuosl.org/pub/cinc/files/stable/cinc/${VERSION}/el/7/cinc-${VERSION}-1.el7.x86_64.rpm \
      CINC_SHA256=${SHA256_AMD64} \
      ;; \
    arm64) \
      CINC_URL=http://ftp-osl.osuosl.org/pub/cinc/files/stable/cinc/${VERSION}/el/7/cinc-${VERSION}-1.el7.aarch64.rpm \
      CINC_SHA256=${SHA256_AARCH64} \
      ;; \
     *) echo "unsupported architecture"; exit 1 ;; \
  esac
  wget -q -O /tmp/cinc-client.rpm ${CINC_URL}
  echo "${CINC_SHA256} cinc.deb" | sha256sum -c -
  rpm2cpio /tmp/cinc-client.rpm | cpio -idmv
  rm -f /tmp/cinc-client.rpm
EOF

VOLUME [ "/opt/cinc" ]

