ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/amazonlinux:2023

# hadolint ignore=DL3041
RUN dnf -y install \
  binutils \
  ca-certificates \
  cronie \
  curl-minimal \
  dmidecode \
  ethtool \
  file \
  fipscheck \
  gnupg2-minimal \
  hostname \
  initscripts \
  iproute \
  iptables \
  iputils \
  less \
  lsof \
  nc \
  net-tools \
  nmap \
  openssl \
  passwd \
  procps \
  strace \
  sudo \
  systemd-sysv \
  systemd-udev \
  tcpdump \
  telnet \
  util-linux \
  vim-minimal \
  wget \
  libxcrypt-compat \
  which && \
  yum upgrade -y && \
  dnf clean all && \
  rm -rf /var/log/* && \
  # Don't start any optional services.
  find /etc/systemd/system \
  /lib/systemd/system \
  -path '*.wants/*' \
  \( -name '*getty*' \
  -or -name '*systemd-logind*' \
  -or -name '*systemd-vconsole-setup*' \
  -or -name '*systemd-readahead*' \
  -or -name '*kdump*' \
  -or -name '*dnf-makecache*' \
  -or -name '*udev*' \) \
  -exec rm -v {} \; && \
  systemctl set-default multi-user.target && \
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service

CMD [ "/usr/lib/systemd/systemd" ]
