# cinc-auditor has its own workflow because it requires a special tag to work
# with Test Kitchen and so it has a unique test harness, specified via the
# "test-image" and "test-entrypoint" parameters.
name: cinc

on:
  push:
    branches: [ main ]
    paths:
      - 'dokken/cinc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'dokken/cinc/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: dokken/cinc
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          test-image: "docker.io/boxcutter/cinc:current"
          test-entrypoint: "/bin/sh"
