# cinc-auditor has its own workflow because it is a prerequisite image for enabling
# the lint stage of our container image pipeline. When we are bootstrapping a new
# setup, this image will not be present in the container registry, nor will the image
# be present for running tests. So we avoid running the lint and test stages of the
# container build pipeline.
name: hadolint

on:
  push:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: hadolint
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          run-lint-stage: false
          run-test-stage: false
