# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:24.04
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS curl

# hadolint ignore=DL3009
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		gnupg \
		netbase \
		sq \
		wget \
# https://bugs.debian.org/929417
		tzdata \
	; \
	apt-get dist-clean

FROM curl AS scm

# hadolint ignore=DL3009
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		mercurial \
		openssh-client \
		subversion \
		\
# procps is very common in build systems, and is a reasonably small package
		procps \
	; \
	apt-get dist-clean

FROM scm AS buildpack-deps

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=SC2046,DL3009
RUN set -ex; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		autoconf \
		automake \
		bzip2 \
		default-libmysqlclient-dev \
		dpkg-dev \
		file \
		g++ \
		gcc \
		imagemagick \
		libbz2-dev \
		libc6-dev \
		libcurl4-openssl-dev \
		libdb-dev \
		libevent-dev \
		libffi-dev \
		libgdbm-dev \
		libglib2.0-dev \
		libgmp-dev \
		libjpeg-dev \
		libkrb5-dev \
		liblzma-dev \
		libmagickcore-dev \
		libmagickwand-dev \
		libmaxminddb-dev \
		libncurses5-dev \
		libncursesw5-dev \
		libpng-dev \
		libpq-dev \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		libtool \
		libwebp-dev \
		libxml2-dev \
		libxslt-dev \
		libyaml-dev \
		make \
		patch \
		unzip \
		xz-utils \
		zlib1g-dev \
	; \
	apt-get dist-clean
