ARG CONTAINER_REGISTRY=docker.io/boxcutter
FROM $CONTAINER_REGISTRY/python:3.9-jammy

ARG FLAKE8_VERSION=6.0.0
WORKDIR /code
RUN python3 -m pip install --no-cache-dir flake8==$FLAKE8_VERSION

ENTRYPOINT ["flake8"]
CMD ["--help"]
