# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20251013
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS base
FROM base AS build

ARG PULUMI_VERSION
RUN <<EOF
  apt-get install -y --update --no-install-recommends \
    ca-certificates \
    curl \
    build-essential \
    git
  rm -rf /var/lib/apt/lists/*
EOF

# Install the Pulumi SDK, including the CLI and language runtimes.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://get.pulumi.com/ | bash -s -- --version $PULUMI_VERSION

# The runtime container
# This is our base container, so let's copy all the runtimes to .pulumi/bin
FROM base

WORKDIR /pulumi
COPY --from=build /root/.pulumi/bin/ bin

RUN --mount=type=cache,target=/var/lib/apt/list \
    --mount=type=cache,target=/var/cache/apt <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    vim
EOF

ENV PATH="/pulumi/bin:${PATH}"
CMD ["pulumi"]
