# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230126 as build

ARG PULUMI_VERSION=3.53.1
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
EOF

# Install the Pulumi SDK, including the CLI and language runtimes.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://get.pulumi.com/ | bash -s -- --version $PULUMI_VERSION

# The runtime container
# This is our base container, so let's copy all the runtimes to .pulumi/bin
FROM $CONTAINER_REGISTRY/boxcutter/python:3.10-jammy

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Pulumi CLI container for python."

WORKDIR /pulumi/projects

RUN --mount=type=cache,target=/var/lib/apt/list \
    --mount=type=cache,target=/var/cache/apt <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    vim
EOF

# Uses the workdir, copies from pulumi interim container
COPY --from=build /root/.pulumi/bin/pulumi /pulumi/bin/pulumi
COPY --from=build /root/.pulumi/bin/*-python* /pulumi/bin/

ENV PATH "/pulumi/bin:${PATH}"
CMD ["pulumi"]
