# syntax=docker/dockerfile:1
ARG LANGUAGE_VERSION=3.13
ARG BUILD_IMAGE=docker.io/ubuntu:noble-20250805
ARG BASE_IMAGE=docker.io/polymathrobotics/python:${LANGUAGE_VERSION}-slim-noble
# hadolint ignore=DL3006
FROM $BUILD_IMAGE AS build

ARG PULUMI_VERSION

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    curl \
    git
EOF

# Install the Pulumi SDK, including the CLI and language runtimes.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://get.pulumi.com/ | bash -s -- --version $PULUMI_VERSION

# The runtime container
# This is our base container, so let's copy all the runtimes to .pulumi/bin
FROM $BASE_IMAGE

WORKDIR /pulumi/projects

RUN <<EOF
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    vim
EOF

# Install poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/usr/local/share/pypoetry python3 -
RUN ln -s /usr/local/share/pypoetry/bin/poetry /usr/local/bin/

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | XDG_BIN_HOME=/usr/local/share/uv bash -s -- --no-modify-path
RUN ln -s /usr/local/share/uv/uv /usr/local/bin/
RUN ln -s /usr/local/share/uv/uvx /usr/local/bin/

# Uses the workdir, copies from pulumi interim container
COPY --from=build /root/.pulumi/bin/pulumi /pulumi/bin/pulumi
COPY --from=build /root/.pulumi/bin/*-python* /pulumi/bin/

ENV PATH="/pulumi/bin:${PATH}"
CMD ["pulumi"]
