ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/oraclelinux:7

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Oracle Linux 7 image for kitchen-dokken"

RUN <<EOF
  yum -y install \
      binutils \
      ca-certificates \
      cronie \
      curl \
      dmidecode \
      ethtool \
      file \
      gnupg2 \
      hostname \
      initscripts \
      iproute \
      iptables \
      iputils \
      less \
      lsof \
      nc \
      net-tools \
      nmap \
      openssl \
      passwd \
      procps \
      strace \
      sudo \
      system-lsb-core \
      systemd-sysv \
      tcpdump \
      telnet \
      util-linux \
      vim-minimal \
      wget \
      which
  yum upgrade -y
  yum clean all
  rm -rf /var/cache/yum
  rm -rf /var/log/*
  find /etc/systemd/system \
      /lib/systemd/system \
      -path '*.wants/*' \
      \( -name '*getty*' \
      -or -name '*sshd*' \
      -or -name '*systemd-logind*' \
      -or -name '*systemd-vconsole-setup*' \
      -or -name '*systemd-readahead*' \
      -or -name '*udev*' \) \
      -exec rm -v {} \;
  systemctl set-default multi-user.target
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service rhnsd.service
EOF

CMD [ "/usr/lib/systemd/systemd" ]
