# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20251013
# hadolint ignore=DL3006
FROM $BASE_IMAGE AS base

ARG BLACKBOX_EXPORTER_URL_AMD64
ARG BLACKBOX_EXPORTER_SHA256_AMD64
ARG BLACKBOX_EXPORTER_URL_ARM64
ARG BLACKBOX_EXPORTER_SHA256_ARM64

FROM base AS download
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  mkdir -p /tmp/blackbox_exporter
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      BLACKBOX_EXPORTER_URL="${BLACKBOX_EXPORTER_URL_AMD64}" \
      BLACKBOX_EXPORTER_SHA256="${BLACKBOX_EXPORTER_SHA256_AMD64}" \
      ;; \
    arm64) \
      BLACKBOX_EXPORTER_URL="${BLACKBOX_EXPORTER_URL_ARM64}" \
      BLACKBOX_EXPORTER_SHA256="${BLACKBOX_EXPORTER_SHA256_ARM64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/blackbox_exporter.tar.gz "${BLACKBOX_EXPORTER_URL}"
  echo "${BLACKBOX_EXPORTER_SHA256} /tmp/blackbox_exporter.tar.gz" | sha256sum -c -
  tar xvf /tmp/blackbox_exporter.tar.gz -C /tmp/blackbox_exporter --strip-components 1
EOF

FROM base

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates
  rm -rf /var/lib/apt/lists/*  
EOF

COPY --chmod=755 --from=download /tmp/blackbox_exporter/blackbox_exporter /usr/local/bin/blackbox_exporter
COPY --from=download /tmp/blackbox_exporter/blackbox.yml /etc/blackbox_exporter/config.yml

EXPOSE 9115
USER nobody
ENTRYPOINT [ "/usr/local/bin/blackbox_exporter" ]
CMD ["--config.file=/etc/blackbox_exporter/config.yml"]
