ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20240212 AS base

ARG ALERTMANAGER_URL_AMD64
ARG ALERTMANAGER_SHA256_AMD64
ARG ALERTMANAGER_URL_ARM64
ARG ALERTMANAGER_SHA256_ARM64
ARG ALERTMANAGER_URL_ARMHF
ARG ALERTMANAGER_SHA256_ARMHF

FROM base as download

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
  && mkdir -p /tmp/alertmanager \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      ALERTMANAGER_URL="$ALERTMANAGER_URL_AMD64" \
      ALERTMANAGER_SHA256="$ALERTMANAGER_SHA256_AMD64" \
      ;; \
    arm64) \
      ALERTMANAGER_URL="$ALERTMANAGER_URL_ARM64" \
      ALERTMANAGER_SHA256="$ALERTMANAGER_SHA256_ARM64" \
      ;; \
    armhf) \
      ALERTMANAGER_URL="$ALERTMANAGER_URL_ARMHF" \
      ALERTMANAGER_SHA256="$ALERTMANAGER_SHA256_ARMHF" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/alertmanager.tar.gz "${ALERTMANAGER_URL}" \
  && echo "${ALERTMANAGER_SHA256} /tmp/alertmanager.tar.gz" | sha256sum -c - \
  && tar xvf /tmp/alertmanager.tar.gz --strip-components 1 -C /tmp/alertmanager

FROM base

WORKDIR /alertmanager

COPY --chmod=755 --from=download /tmp/alertmanager/amtool /usr/local/bin/amtool
COPY --chmod=755 --from=download /tmp/alertmanager/alertmanager /usr/local/bin/alertmanager
COPY --from=download /tmp/alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && chown -R nobody:nogroup /etc/alertmanager /alertmanager

USER nobody
EXPOSE 9093
VOLUME [ "/alertmanager" ]
ENTRYPOINT [ "/usr/local/bin/alertmanager" ]
CMD [ "--config.file=/etc/alertmanager/alertmanager.yml", \
      "--storage.path=/alertmanager" ]
