# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20251001
FROM ${BASE_IMAGE} AS base

FROM base AS build

ARG DOCTL_URL_AMD64
ARG DOCTL_SHA256_AMD64
ARG DOCTL_URL_ARM64
ARG DOCTL_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCTL_URL="${DOCTL_URL_AMD64}" \
      DOCTL_SHA256="${DOCTL_SHA256_AMD64}" \
      KUBECTL_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
      KUBECTL_SHA256_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" \
      ;; \
    arm64) \
      DOCTL_URL="${DOCTL_URL_ARM64}" \
      DOCTL_SHA256="${DOCTL_SHA256_AMD64}" \
      KUBECTL_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl" \
      KUBECTL_SHA256_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl.sha256" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/doctl.tar.gz ${DOCTL_URL}
  echo "${DOCTL_SHA256} /tmp/doctl.tar.gz" | sha256sum -c -
  mkdir -p /tmp/doctl
  tar xzvf /tmp/doctl.tar.gz -C /tmp/doctl

  curl -fsSL -o /tmp/kubectl ${KUBECTL_URL}
  curl -fsSL -o /tmp/kubectl.sha256 ${KUBECTL_SHA256_URL}
  echo "$(cat /tmp/kubectl.sha256)  /tmp/kubectl" | sha256sum -c -

  rm -rf /var/lib/apt/lists/*
EOF

FROM base

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client
  rm -rf /var/lib/apt/lists/*
EOF

RUN useradd -m doctl
USER doctl
WORKDIR /home/doctl

COPY --from=build --chmod=0755 /tmp/doctl/doctl /usr/local/bin/doctl
COPY --from=build --chmod=0755 /tmp/kubectl /usr/local/bin/kubectl

CMD ["/usr/local/bin/doctl"]
