# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20240801
FROM ${BASE_IMAGE} AS base

FROM base AS build

ARG DOCTL_URL_AMD64
ARG DOCTL_SHA256_AMD64
ARG DOCTL_URL_ARM64
ARG DOCTL_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCTL_URL="${DOCTL_URL_AMD64}" \
      DOCTL_SHA256="${DOCTL_SHA256_AMD64}" \
      ;; \
    arm64) \
      DOCTL_URL="${DOCTL_URL_ARM64}" \
      DOCTL_SHA256="${DOCTL_SHA256_AMD64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/doctl.tar.gz ${DOCTL_URL}
  echo "${DOCTL_SHA256} /tmp/doctl.tar.gz" | sha256sum -c -
  mkdir -p /tmp/doctl
  tar xzvf /tmp/doctl.tar.gz -C /tmp/doctl
  rm -rf /var/lib/apt/lists/*
EOF

FROM base

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /app
COPY --from=build /tmp/doctl/doctl /usr/local/bin/doctl

ENTRYPOINT ["/usr/local/bin/doctl"]
