# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308 AS build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCTL_URL='https://github.com/digitalocean/doctl/releases/download/v1.93.1/doctl-1.93.1-linux-amd64.tar.gz' \
      DOCTL_SHA256='b84c96443815a4ee8857c82eba47e36cec953eb9d3f5c542a2c2ab9868f40f4f' \
      ;; \
    arm64) \
      DOCTL_URL='https://github.com/digitalocean/doctl/releases/download/v1.93.1/doctl-1.93.1-linux-arm64.tar.gz' \
      DOCTL_SHA256='6ea1955fd2e63937101549b6895272b71f21c83f3563cc9911f1b1891b34690c' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/doctl.tar.gz ${DOCTL_URL}
  echo "${DOCTL_SHA256} /tmp/doctl.tar.gz" | sha256sum -c -
  mkdir -p /tmp/doctl
  tar xzvf /tmp/doctl.tar.gz -C /tmp/doctl
EOF

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Digital Ocean command-line interface."

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    openssh-client
  rm -rf /var/lib/apt/lists/*
EOF

WORKDIR /app
COPY --from=build /tmp/doctl/doctl /usr/local/bin/doctl

ENTRYPOINT ["/usr/local/bin/doctl"]
