# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/boxcutter/python:3.13-noble
# hadolint ignore=DL3006
FROM $BASE_IMAGE AS base

ARG BLACK_VERSION
WORKDIR /code
RUN python3 -m pip install --no-cache-dir black==$BLACK_VERSION

ENTRYPOINT  ["black"]
