# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io/boxcutter
FROM $CONTAINER_REGISTRY/python:3.9-jammy

ARG BLACK_VERSION
WORKDIR /code
RUN python3 -m pip install --no-cache-dir black==$BLACK_VERSION

ENTRYPOINT  ["black"]
