# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY
FROM ${CONTAINER_REGISTRY:-docker.io}/ubuntu:noble-20240801 AS build

ARG SHELLCHECK_URL_AMD64
ARG SHELLCHECK_URL_ARM64
ARG SHELLCHECK_URL_ARMHF

# hadolint ignore=SC2086
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    xz-utils \
  && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) \
      SHELLCHECK_URL="$SHELLCHECK_URL_AMD64" \
      ;; \
    arm64) \
      SHELLCHECK_URL="$SHELLCHECK_URL_ARM64" \
      ;; \
    armhf) \
      SHELLCHECK_URL="$SHELLCHECK_URL_ARMHF" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
  && curl -fsSL -o /tmp/shellcheck.tar.gz ${SHELLCHECK_URL} \
  && tar -xf /tmp/shellcheck.tar.gz --wildcards '*/shellcheck' --strip-components=1

FROM scratch

COPY --from=build /shellcheck /usr/local/bin/shellcheck

WORKDIR /share
ENTRYPOINT ["/usr/local/bin/shellcheck"]
