# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 as base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    xz-utils
  rm -rf /var/lib/apt/lists/*
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      HADOLINT_URL=https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 \
      HADOLINT_SHA256='56de6d5e5ec427e17b74fa48d51271c7fc0d61244bf5c90e828aab8362d55010' \
      ;; \
    arm64) \
      HADOLINT_URL=https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-arm64 \
      HADOLINT_SHA256='5798551bf19f33951881f15eb238f90aef023f11e7ec7e9f4c37961cb87c5df6' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /usr/local/bin/hadolint -L ${HADOLINT_URL}
  chmod +x /usr/local/bin/hadolint
  echo "${HADOLINT_SHA256} /usr/local/bin/hadolint" | sha256sum -c -
EOF

FROM base as lint
COPY --from=base --chmod=777 /usr/local/bin/hadolint /usr/local/bin/hadolint
COPY Containerfile /

RUN /usr/local/bin/hadolint --ignore DL3008 --ignore DL3033 --ignore DL3059 Containerfile

FROM base as release
COPY --from=base --chmod=777 /usr/local/bin/hadolint /usr/local/bin/hadolint
WORKDIR /shared
COPY hadolint.yaml .hadolint.yaml
CMD ["/bin/hadolint", "-"]
