# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20251013
FROM $BASE_IMAGE AS base

FROM base AS download

ARG HADOLINT_URL_AMD64
ARG HADOLINT_SHA256_AMD64
ARG HADOLINT_URL_ARM64
ARG HADOLINT_SHA256_ARM64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get install --update --no-install-recommends -y \
    ca-certificates \
    curl \
    xz-utils
  rm -rf /var/lib/apt/lists/*
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      HADOLINT_URL="${HADOLINT_URL_AMD64}" \
      HADOLINT_SHA256="${HADOLINT_SHA256_AMD64}" \
      ;; \
    arm64) \
      HADOLINT_URL="${HADOLINT_URL_ARM64}" \
      HADOLINT_SHA256="${HADOLINT_SHA256_ARM64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /usr/local/bin/hadolint -L ${HADOLINT_URL}
  chmod +x /usr/local/bin/hadolint
  echo "${HADOLINT_SHA256} /usr/local/bin/hadolint" | sha256sum -c -
EOF

FROM base
COPY --from=download --chmod=777 /usr/local/bin/hadolint /usr/local/bin/hadolint
WORKDIR /shared
COPY hadolint.yaml .hadolint.yaml
CMD ["/bin/hadolint", "-"]
