# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io/boxcutter
FROM $CONTAINER_REGISTRY/ruby:3.1-slim-jammy

ARG MARKDOWNLINT_VERSION

RUN gem install mdl --no-document -v $MARKDOWNLINT_VERSION

RUN useradd -ms /sbin/nologin mdl

USER mdl

WORKDIR  /data

ENTRYPOINT ["mdl"]
CMD ["--help"]
