# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20220815 as build

RUN <<EOF
  apt-get update
  apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    xz-utils
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.26.1/dasel_linux_amd64 \
      ;; \
    arm64) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.26.1/dasel_linux_arm64 \
      ;; \
    armhf) \
      DASEL_URL=https://github.com/TomWright/dasel/releases/download/v1.26.1/dasel_linux_arm32 \
      ;;
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/dasel ${DASEL_URL}
EOF


FROM $CONTAINER_REGISTRY/ubuntu:jammy-20220815

LABEL \
    org.opencontainers.image.source="https://github.com/polymathrobotics/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Command line processor for JSON, YAML, TOML, XML and CSV."

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends jq
  rm -rf /var/lib/apt/lists/*
EOF

COPY --chmod=755 --from=build /tmp/dasel /usr/local/bin/dasel

ENTRYPOINT ["/usr/local/bin/dasel"]
CMD ["--help"]
VOLUME ["/share"]
WORKDIR /share
