#syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231211.1 AS base

ARG BLACKBOX_EXPORTER_URL_AMD64="https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-amd64.tar.gz"
ARG BLACKBOX_EXPORTER_SHA256_AMD64="81b36cece040491ac0d9995db2a0964c40e24838a03a151c3333a7dc3eef94ff"
ARG BLACKBOX_EXPORTER_URL_ARM64="https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-arm64.tar.gz"
ARG BLACKBOX_EXPORTER_SHA256_ARM64="acbbedf03de862fa833bc4dd810e63f105cb44e47abf493192fce3451852dc58"
ARG BLACKBOX_EXPORTER_URL_ARMHF="https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-armv7.tar.gz"
ARG BLACKBOX_EXPORTER_SHA256_ARMHF="13b6652f69b6ab3d0f84440a893446679662c6f8b4cca360363c41baa4028638"

FROM base as download
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  mkdir -p /tmp/blackbox_exporter
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      BLACKBOX_EXPORTER_URL="${BLACKBOX_EXPORTER_URL_AMD64}" \
      BLACKBOX_EXPORTER_SHA256="${BLACKBOX_EXPORTER_SHA256_AMD64}" \
      ;; \
    arm64) \
      BLACKBOX_EXPORTER_URL="${BLACKBOX_EXPORTER_URL_ARM64}" \
      BLACKBOX_EXPORTER_SHA256="${BLACKBOX_EXPORTER_SHA256_ARM64}" \
      ;; \
    armhf) \
      BLACKBOX_EXPORTER_URL="${BLACKBOX_EXPORTER_URL_ARMHF}" \
      BLACKBOX_EXPORTER_SHA256="${BLACKBOX_EXPORTER_SHA256_ARMHF}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o /tmp/blackbox_exporter.tar.gz ${BLACKBOX_EXPORTER_URL}
  echo "${BLACKBOX_EXPORTER_SHA256} /tmp/blackbox_exporter.tar.gz" | sha256sum -c -
  tar xvf /tmp/blackbox_exporter.tar.gz -C /tmp/blackbox_exporter --strip-components 1
EOF

FROM base

RUN <<EOF
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates
  rm -rf /var/lib/apt/lists/*  
EOF

COPY --chmod=755 --from=download /tmp/blackbox_exporter/blackbox_exporter /usr/local/bin/blackbox_exporter
COPY --from=download /tmp/blackbox_exporter/blackbox.yml /etc/blackbox_exporter/config.yml

EXPOSE 9115
USER nobody
ENTRYPOINT [ "/usr/local/bin/blackbox_exporter" ]
CMD ["--config.file=/etc/blackbox_exporter/config.yml"]