# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/eurolinux/eurolinux-7
FROM ${BASE_IMAGE}

# hadolint ignore=DL3041
RUN <<EOF
  yum -y install \
    binutils \
    ca -certificates \
    cronie \
    curl \
    dmidecode \
    e2fsprogs \
    ethtool \
    file \
    gnupg2 \
    hostname \
    initscripts \
    iproute \
    iptables \
    iputils \
    less \
    lsof \
    nc \
    net-tools \
    nmap \
    openssl \
    passwd \
    procps \
    strace \
    sudo \
    system-lsb-core \
    systemd-sysv \
    tcpdump \
    telnet \
    util-linux \
    vim-minimal \
    wget \
    libxcrypt-compat \
    which
  yum upgrade -y
  yum clean all
  m -rf /var/cache/yum
  rm -rf /var/log/*
  find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    \( -name '*getty*' \
    -or -name '*systemd-logind*' \
    -or -name '*systemd-vconsole-setup*' \
    -or -name '*systemd-readahead*' \
    -or -name '*udev*' \) \
    -exec rm -v \{} \;
  systemctl set-default multi-user.target 
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service
EOF

CMD [ "/usr/lib/systemd/systemd" ]
