# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io

FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 AS base
FROM base AS ros-core

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# setup sources.list
RUN echo "deb http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2-latest.list

# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO iron

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-ros-core=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*

# setup entrypoint
COPY ./ros_entrypoint.sh /

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

FROM ros-core as ros-base

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init && \
  rosdep update --rosdistro $ROS_DISTRO

# setup colcon mixin and metadata
RUN colcon mixin add default \
      https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update && \
    colcon metadata add default \
      https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
    colcon metadata update

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-ros-base=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*

FROM ros-base as perception

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-perception=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*

FROM ros-base as simulation

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-simulation=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*

FROM ros-base as desktop

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-desktop=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*

FROM desktop as desktop-full

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-iron-desktop-full=0.10.0-3* \
    && rm -rf /var/lib/apt/lists/*