[container_image]
name = "jupyter-base-notebook"
tags = [ "python-3.10.9", "python-3.10", "hub-3.1.1", "lab-3.6.1", "ubuntu-22.04", "notebook-6.5.2", "latest" ]
platforms = ["linux/arm64", "linux/amd64"]
readme = "jupyter/README.md"

