ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/eurolinux/eurolinux-9

# hadolint ignore=DL3041
RUN <<EOF
  dnf -y install \
    at \
    binutils \
    bc \
    ca-certificates \
    cronie \
    crontabs \
    diffutils \
    dmidecode \
    e2fsprogs \
    ed \
    ethtool \
    file \
    gettext \
    glibc-langpack-en \
    gnupg2 \
    hostname \
    initscripts \
    iproute \
    iptables \
    iputils \
    lsof \
    nc \
    net-tools \
    nmap \
    make \
    man-db \
    openssl \
    patch \
    passwd \
    procps \
    procps-ng \
    psmisc \
    policycoreutils \
    strace \
    sudo \
    systemd-sysv \
    systemd-udev \
    tcpdump \
    telnet \
    util-linux \
    vim-minimal \
    time \
    wget \
    libxcrypt-compat \
    which
  dnf upgrade -y
  dnf clean all
  rm -rf /var/log/*
  find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    \( -name '*getty*' \
    -or -name '*systemd-logind*' \
    -or -name '*systemd-vconsole-setup*' \
    -or -name '*systemd-readahead*' \
    -or -name '*kdump*' \
    -or -name '*dnf-makecache*' \
    -or -name '*udev*' \) \
    -exec rm -v \{} \;
  systemctl set-default multi-user.target 
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service systemd-journal-flush.service
EOF

CMD [ "/usr/lib/systemd/systemd" ]
