# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20230308

LABEL \
    org.opencontainers.image.source="https://github.com/boxcutter/oci" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.description="Base image with all the prerequisite tools for TeX Live (does not include TeX Live applications/packages)."

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    # ConTeXt cache can be created on runtime and does not need to
    # increase image size
    TEXLIVE_INSTALL_NO_CONTEXT_CACHE=1 \
    # As we will not install regular documentation why would we want to
    # install perl docs…
    NOPERLDOC=1

RUN apt-get update && \
  # basic utilities for TeX Live installation
  apt-get install -qy --no-install-recommends curl git unzip \
  # miscellaneous dependencies for TeX Live tools
  make fontconfig perl default-jre libgetopt-long-descriptive-perl \
  libdigest-perl-md5-perl libncurses5 libncurses6 \
  # for latexindent (see #13)
  libunicode-linebreak-perl libfile-homedir-perl libyaml-tiny-perl \
  # for eps conversion (see #14)
  ghostscript \
  # for metafont (see #24)
  libsm6 \
  # for syntax highlighting
  python3 python3-pygments \
  # for gnuplot backend of pgfplots (see !13)
  gnuplot-nox && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/apt/ && \
  # bad fix for python handling
  ln -s /usr/bin/python3 /usr/bin/python
