# syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20220815

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    # ConTeXt cache can be created on runtime and does not need to
    # increase image size
    TEXLIVE_INSTALL_NO_CONTEXT_CACHE=1 \
    # As we will not install regular documentation why would we want to
    # install perl docs…
    NOPERLDOC=1

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    default-jre \
    fontconfig \
    ghostscript \
    git \
    gnuplot-nox \
    libdigest-perl-md5-perl \
    libfile-homedir-perl \
    libgetopt-long-descriptive-perl \
    libncurses5 \
    libncurses6 \
    libsm6 \
    libunicode-linebreak-perl \
    libyaml-tiny-perl \
    make \
    perl \
    python3 \
    python3-pygments \
    unzip
EOF
