# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/debian:trixie
FROM ${BASE_IMAGE}

# hadolint ignore=DL3015
RUN <<EOF
  DEBIAN_FRONTEND=noninteractive apt-get -y --update install \
    apt-utils \
    cron \
    curl \
    dbus \
    dirmngr \
    dmidecode \
    gnupg \
    ifupdown \
    iptables \
    iputils-ping \
    kmod \
    less \
    locales \
    lsb-release \
    lsof \
    net-tools \
    nmap \
    perl \
    procps \
    strace \
    sudo \
    systemd \
    tcpdump \
    telnet \
    tzdata \
    udev \
    vim-tiny \
    wget
  apt-get clean
  apt-get -y autoremove
  rm -rf /tmp/* /var/tmp/*
  find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    \( -name '*getty*' \
    -or -name '*apt-daily*' \
    -or -name '*dpkg-db-backup*' \
    -or -name '*systemd-timesyncd*' \
    -or -name '*systemd-logind*' \
    -or -name '*systemd-vconsole-setup*' \
    -or -name '*systemd-readahead*' \
    -or -name '*udev*' \) \
    -exec rm -v {} \;
  systemctl set-default multi-user.target
  systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount network.service systemd-journal-flush.service
EOF

CMD [ "/usr/lib/systemd/systemd" ]
