# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20240801
FROM $BASE_IMAGE

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    fdisk \
    xorriso
EOF

COPY image-create.sh /app/

VOLUME /data
WORKDIR /data

ENTRYPOINT [ "/app/image-create.sh" ]
