#syntax=docker/dockerfile:1
ARG CONTAINER_REGISTRY=docker.io
FROM $CONTAINER_REGISTRY/ubuntu:jammy-20231004 AS build

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  mkdir -p /tmp/meshcmd
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      MESHCMD_URL='https://meshcentral.com/executables/meshcmd-linux-x86-64' \
      ;; \
    arm64) \
      MESHCMD_URL='https://meshcentral.com/executables/meshcmd-linux-arm-64' \
      ;; \
    armhf) \
      MESHCMD_URL='https://meshcentral.com/executables/meshcmd-linux-arm-32' \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac
  curl -o /tmp/meshcmd/meshcmd "$MESHCMD_URL"
  rm -rf /var/lib/apt/lists/*
EOF

FROM build

WORKDIR /opt/meshcmd/bin

COPY --from=build --chmod=755 /tmp/meshcmd /opt/meshcmd/bin

ENV PATH "/opt/meshcmd/bin:${PATH}"
EXPOSE 3000

ENTRYPOINT ["meshcmd"]
