# syntax=docker/dockerfile:1
ARG BASE_IMAGE=docker.io/ubuntu:noble-20250716
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS base

ARG GLAB_URL_AMD64
ARG GLAB_SHA256_AMD64
ARG GLAB_URL_ARM64
ARG GLAB_SHA256_ARM64
ARG DOCKER_URL_AMD64
ARG DOCKER_URL_ARM64

FROM base AS download

WORKDIR /tmp

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      GLAB_URL="${GLAB_URL_AMD64}" \
      GLAB_SHA256="${GLAB_SHA256_AMD64}" \
      ;; \
    arm64) \
      GLAB_URL="${GLAB_URL_ARM64}" \
      GLAB_SHA256="${GLAB_SHA256_ARM64}" \
      ;; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac 
  curl -fsSL -o glab.deb "${GLAB_URL}"
  echo "${GLAB_SHA256} glab.deb" | sha256sum -c -
EOF

RUN <<EOF
  dpkgArch="$(dpkg --print-architecture)"
  case "${dpkgArch##*-}" in \
    amd64) \
      DOCKER_URL="$DOCKER_URL_AMD64" \
      ;; \
    arm64) \
      DOCKER_URL="$DOCKER_URL_ARM64" \
      ;;
    *) echo "unsupported architecture"; exit 1 ;; \
  esac
  curl -fsSL -o docker.tgz "${DOCKER_URL}"
  tar --extract \
		--file docker.tgz \
		--strip-components 1 \
		--directory /usr/local/bin/ \
		--no-same-owner \
		'docker/docker'
  docker --version 
EOF

FROM base

COPY --from=download /tmp/glab.deb /tmp/glab.deb
COPY --from=download /usr/local/bin/docker /usr/local/bin/docker
COPY --chmod=744 entrypoint.sh /entrypoint.sh

RUN <<EOF
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    jq \
    openssh-client
  dpkg -i /tmp/glab.deb
  rm -rf /var/lib/apt/lists/*
EOF

ENTRYPOINT ["/entrypoint.sh"]
CMD [ "-h" ]

