name: Lint GitHub Actions Workflows

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Run actionlint
        run: actionlint -color
