# cinc-auditor has its own workflow because it is a prerequisite image for enabling
# the test stage of our container image pipeline. When we are bootstrapping a new
# setup, this image will not be present in the container registry. So we avoid running
# the test stage of the container build pipeline.
name: cinc-auditor

on:
  push:
    branches: [ main ]
    paths:
      - 'cinc/cinc-auditor/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cinc/cinc-auditor/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: cinc/cinc-auditor
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          run-test-stage: false
