name: cinc

on:
  push:
    branches: [ main ]
    paths:
      - 'cinc/cinc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cinc/cinc/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: cinc/cinc
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          test-image: "docker.io/boxcutter/cinc:current"
          test-entrypoint: "/bin/sh"
