name: cinc-auditor

on:
  push:
    branches: [ main ]
    paths:
      - 'cinc/cinc-auditor/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cinc/cinc-auditor/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: cinc/cinc-auditor
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          run-test-stage: false
