# cinc-auditor has its own workflow because it requires a special tag to work
# with Test Kitchen and so it has a unique test harness, specified via the
# "test-image" and "test-entrypoint" parameters.
name: cinc

on:
  push:
    branches: [ main ]
    paths:
      - 'dokken/cinc/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'dokken/cinc/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}

      - name: Set up Docker Buildx for Cloud
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "boxcutter/testy"
          install: true

      - name: Run `docker buildx bake` with Docker Cloud
        run: |
          docker buildx bake --builder cloud --push --progress=plain
