name: hadolint

on:
  push:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hadolint
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: polymathrobotics/hadolint

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/bake-action@v4
        with:
          workdir: hadolint
          push: true

      - name: Update Docker Hub Description
        if: github.event_name == 'push'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          repository: boxcutter/hadolint
