name: hadolint

on:
  push:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'hadolint/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: boxcutter/container-build-publish-action@main
        with:
          workdir: hadolint
          dockerhub-username: ${{ secrets.CONTAINER_DESCRIPTION_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          run-lint-stage: false
          run-test-stage: false
