name: Manual Builds

on:
  workflow_dispatch:
    inputs:
      list:
        description: 'Comma-separated list of directories'
        required: true
        default: ''

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - id: set-matrix
        run: |
          repos='${{ toJSON(github.event.inputs.list) }}'
          echo "matrix=$repos" >> $GITHUB_OUTPUT
          echo "MISCHA $repos"
          # IFS=',' read -ra ADDR <<< "${{ github.event.inputs.list }}"
          # MATRIX_JSON=$(printf '[%s]' "$(printf '{"item":"%s"},' "${ADDR[@]}")")
          # MATRIX_JSON="${MATRIX_JSON%,}" # Remove the last comma
          # echo "MISCHA $MATRIX_JSON"
          # echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       directory: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
    - run: |
        echo "MISCHA: ${{ matrix.directory }}"
