name: Manual Builds

on:
  workflow_dispatch:
    inputs:
      directories:
        description: 'Comma-separated list of directories'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       directory: ${{ fromJSON(format('[{0}]', github.event.inputs.directories)) }}
    steps:
    - run: |
        echo "MISCHA"
