name: Manual Builds

on:
  workflow_dispatch:
    inputs:
      list:
        description: 'Comma-separated list of directories'
        required: true
        default: ''

jobs:          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       directory: ${{ fromJSON(github.event.inputs.list) }}
    steps:
    - run: |
        echo "MISCHA: ${{ matrix.directory }}"
