name: Manual Builds

on:
  workflow_dispatch:
    inputs:
      directories:
        description: 'Comma-separated list of directories'
        required: true
        default: ''

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "MISCHA ${{ toJSON(github.event.inputs.directories) }}"
