name: ros

on:
  push:
    branches: [ main ]
    paths:
      - 'ros/humble/ubuntu/jammy/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ros/humble/ubuntu/jammy/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ros/humble/ubuntu/jammy
    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
