name: shellcheck

on:
  push:
    branches: [ main ]
    paths:
      - 'shellcheck/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'shellcheck/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shellcheck
    steps:
      - uses: boxcutter/container-build-publish-action
